TextMate_NN equivalent_JJ to_TO gVim_FW Ctrl+P_FW
To_TO auto_NN complete_VB a_DT previously_RB written_VBN string_NN ._. Is_VBZ it_PRP possible_JJ ?_. EDIT_FW I'm_FW editing_NN javascript_NN /_: java_NN if_IN that_DT matters_NNS ._.
Yes_NNP -_: the_DT autocomplete_NN key_NN is_VBZ '_POS escape_NN '_'' by_IN default_NN ._. See_VB the_DT TextMate_NNP manual_NN for_IN further_JJ information_NN ._.
Thank_VB you_PRP !!!_VBP it_PRP was_VBD driving_VBG me_PRP crazy_JJ !!!_FW :)_FW About_IN the_DT manual_NN ..._: mhhhh_NN ..._: mmhh_JJ well_NN .._NN Beside_IN having_VBG to_TO write_VB my_PRP$ own_JJ product_NN user_NN manual_FW (_FW which_WDT I_PRP hate_VBP and_CC usually_RB I_PRP avoid_VBP )_NN do_VBP I_PRP have_VB to_TO read_VB others_NNS them_PRP too_RB ???_FW :)_FW :)_FW :)_FW ;)_FW Thanks_NNS again_RB
@Oscar_NN -_: absolutely_RB ._. RTFM_NN ,_, man_NN ._.
Also_RB ,_, Google_NNP "_`` Textmate_NN tips_NNS "_'' -_: I_PRP seem_VBP to_TO pick_VB up_RP something_NN new_JJ in_IN every_DT blogpost_NN I_PRP read_VBP about_IN TM_NN ._.
Thanks_NNS for_IN the_DT hint_NN ._. I_PRP didn't_VBP know_VB about_IN http://textmatetips.com_NNP ._.
