render_VB complex_JJ org_NN chart_NN similar_JJ javascript_NN /_: flash_NN /_: java_JJ graphic_JJ library_NN
i_LS am_RB looking_VBG for_IN javascript_NN /_: flash_NN /_: java_JJ graphic_JJ lib_NN ._. that_IN able_JJ to_TO render_VB nicely_RB a_DT very_RB complex_JJ relationship_NN where_WRB one_CD node_NN is_VBZ relate_VB to_TO another_DT node_NN etc_NN ._. for_IN example_NN a_DT -->_TO b_NN --->_CD c_NN b_NN -->_TO d_NN ,_, e_LS ,_, f_SYM any_DT recommandation_NN library_NN ?_.
So_RB essentially_RB you_PRP are_VBP looking_VBG for_IN recommendations_NNS for_IN a_DT graph_NN visualization_NN library_NN for_IN Javascript_NNP ,_, Flash_NNP ,_, or_CC Java_NNP ?_.
yes.i_NNS am_VBP looking_VBG for_IN graph_NN visualization_NN lib_NN
what_WP a_DT cooincidence_NN ,_, I_PRP was_VBD just_RB looking_VBG into_IN this_DT myself_PRP ._. I_PRP found_VBD this_DT :_: http://www.ryandesign.com/canviz_NN http://code.google.com/p/canviz_NN /_:
Prefuse_NNP is_VBZ very_RB cool_JJ and_CC Java_NNP based_VBN ._. Demo_NNP here_RB ._.
This_DT is_VBZ the_DT one_CD I_NN use_NN for_IN Organizational_JJ chart_NN http://code.google.com/apis/visualization/documentation/gallery/orgchart.html_NN
The_DT Graphviz_NNP open_JJ source_NN graph_NN visualization_NN software_NN is_VBZ widely_RB used_VBN to_TO render_VB graphs_NNS ,_, and_CC jGraphviz_NN is_VBZ a_DT binding_NN for_IN java_NN ._.
